//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResxPackage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public DialogRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResxPackage.Resources.DialogRes", typeof(DialogRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected cultures.
        /// </summary>
        public static string AddSelectedCultures {
            get {
                return ResourceManager.GetString("AddSelectedCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed resource files will be added for selected cultures..
        /// </summary>
        public static string AddSelectedCultures_Tooltip {
            get {
                return ResourceManager.GetString("AddSelectedCultures_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Table.
        /// </summary>
        public static string CreateNewTable {
            get {
                return ResourceManager.GetString("CreateNewTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultures.
        /// </summary>
        public static string Cultures {
            get {
                return ResourceManager.GetString("Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect to google service. 
        ///                   
        ///This can take up to 3-10 seconds. 
        ///                   
        ///Please wait.
        /// </summary>
        public static string DelayText {
            get {
                return ResourceManager.GetString("DelayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No document selected.
        /// </summary>
        public static string DocumentNotSelected {
            get {
                return ResourceManager.GetString("DocumentNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeed sub cultures.
        /// </summary>
        public static string EmbeedSubCultures {
            get {
                return ResourceManager.GetString("EmbeedSubCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked than sub cultures like Resources.EN.resx. will be embeeded as subfile to Resources.resx. If unchecked embeeding will be removed..
        /// </summary>
        public static string EmbeedSubCultures_Tooltip {
            get {
                return ResourceManager.GetString("EmbeedSubCultures_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Excel {
            get {
                object obj = ResourceManager.GetObject("Excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export/import to/from excel file..
        /// </summary>
        public static string ExcelTooltip {
            get {
                return ResourceManager.GetString("ExcelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExportToExcel {
            get {
                object obj = ResourceManager.GetObject("ExportToExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports resources data to excel file. Please save excel file format!.
        /// </summary>
        public static string ExportToExcelTooltip {
            get {
                return ResourceManager.GetString("ExportToExcelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ExportToGSheets {
            get {
                object obj = ResourceManager.GetObject("ExportToGSheets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports resources data to google sheets document..
        /// </summary>
        public static string ExportToGSheetsTooltip {
            get {
                return ResourceManager.GetString("ExportToGSheetsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GSheets {
            get {
                object obj = ResourceManager.GetObject("GSheets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export/import to/from google sheets..
        /// </summary>
        public static string GSheetsTooltip {
            get {
                return ResourceManager.GetString("GSheetsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports updated resources data from excel file..
        /// </summary>
        public static string ImportFromExcelTooltip {
            get {
                return ResourceManager.GetString("ImportFromExcelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports updated resources data from google sheets document..
        /// </summary>
        public static string ImportFromGSheetsTooltip {
            get {
                return ResourceManager.GetString("ImportFromGSheetsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImpotrFromExcel {
            get {
                object obj = ResourceManager.GetObject("ImpotrFromExcel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImpotrFromGSheets {
            get {
                object obj = ResourceManager.GetObject("ImpotrFromGSheets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser navigation failed.
        /// </summary>
        public static string NavgationFailed {
            get {
                return ResourceManager.GetString("NavgationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Sheets access permissions.
        /// </summary>
        public static string PermissionsRequest {
            get {
                return ResourceManager.GetString("PermissionsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select destanation document..
        /// </summary>
        public static string PleaseSelectDocument {
            get {
                return ResourceManager.GetString("PleaseSelectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove not selected cultures.
        /// </summary>
        public static string RemoveNotSelectedCultures {
            get {
                return ResourceManager.GetString("RemoveNotSelectedCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected culture resource files will be removed during synchronization..
        /// </summary>
        public static string RemoveNotSelectedCultures_Tooltip {
            get {
                return ResourceManager.GetString("RemoveNotSelectedCultures_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ResxGen {
            get {
                object obj = ResourceManager.GetObject("ResxGen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize resources..
        /// </summary>
        public static string ResxSyncTooltip {
            get {
                return ResourceManager.GetString("ResxSyncTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Document.
        /// </summary>
        public static string SelectDocument {
            get {
                return ResourceManager.GetString("SelectDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize resources content.
        /// </summary>
        public static string SyncResourcesContent {
            get {
                return ResourceManager.GetString("SyncResourcesContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources content for different cultures will be synchronized. It means that resource keys missed in default culture resource will be removed for subcultures and keys missed in subculture will be copied from default culture..
        /// </summary>
        public static string SyncResourcesContent_Tooltip {
            get {
                return ResourceManager.GetString("SyncResourcesContent_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command adds new selected cultures files and strings and removes not selected cultures..
        /// </summary>
        public static string SyncResourcesTooltip {
            get {
                return ResourceManager.GetString("SyncResourcesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default content type.
        /// </summary>
        public static string UseDefaultContentType {
            get {
                return ResourceManager.GetString("UseDefaultContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked than content type of all culture resources will be changed to &quot;Embedded Resource&quot;. If unchecked content type will be changed to &quot;None&quot;..
        /// </summary>
        public static string UseDefaultContentType_Tooltip {
            get {
                return ResourceManager.GetString("UseDefaultContentType_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default custom tool.
        /// </summary>
        public static string UseDefaultCustomTool {
            get {
                return ResourceManager.GetString("UseDefaultCustomTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked than custom tool property of all neutral resources will be changed to &quot;PublicResXFileCodeGenerator&quot;. If unchecked custom tool property will be seted to empty string..
        /// </summary>
        public static string UseDefaultCustomTool_Tooltip {
            get {
                return ResourceManager.GetString("UseDefaultCustomTool_Tooltip", resourceCulture);
            }
        }
    }
}
