//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResxPackage.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatusRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResxPackage.Resources.StatusRes", typeof(StatusRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating cells map....
        /// </summary>
        public static string CreatingCellsMap {
            get {
                return ResourceManager.GetString("CreatingCellsMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting old worksheets....
        /// </summary>
        public static string DeletingOldWorksheets {
            get {
                return ResourceManager.GetString("DeletingOldWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to excel....
        /// </summary>
        public static string ExportingToExcel {
            get {
                return ResourceManager.GetString("ExportingToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to google drive....
        /// </summary>
        public static string ExportToGDrive {
            get {
                return ResourceManager.GetString("ExportToGDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating resource files....
        /// </summary>
        public static string GeneratingResx {
            get {
                return ResourceManager.GetString("GeneratingResx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting project resources....
        /// </summary>
        public static string GettingProjectsResources {
            get {
                return ResourceManager.GetString("GettingProjectsResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting spreadsheet....
        /// </summary>
        public static string GettingSpreadsheet {
            get {
                return ResourceManager.GetString("GettingSpreadsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting worksheets....
        /// </summary>
        public static string GettingWorksheets {
            get {
                return ResourceManager.GetString("GettingWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting worksheets data....
        /// </summary>
        public static string GettingWorksheetsData {
            get {
                return ResourceManager.GetString("GettingWorksheetsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing from google drive....
        /// </summary>
        public static string ImportFromGDrive {
            get {
                return ResourceManager.GetString("ImportFromGDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting new worksheets....
        /// </summary>
        public static string InsertingNewWorksheets {
            get {
                return ResourceManager.GetString("InsertingNewWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merging resources....
        /// </summary>
        public static string MergingResources {
            get {
                return ResourceManager.GetString("MergingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing resources to export....
        /// </summary>
        public static string PreparingResourcesToExport {
            get {
                return ResourceManager.GetString("PreparingResourcesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushing data....
        /// </summary>
        public static string PushingCells {
            get {
                return ResourceManager.GetString("PushingCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming old worksheets....
        /// </summary>
        public static string RenamingOldWorksheets {
            get {
                return ResourceManager.GetString("RenamingOldWorksheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating cells....
        /// </summary>
        public static string UpdatingCells {
            get {
                return ResourceManager.GetString("UpdatingCells", resourceCulture);
            }
        }
    }
}
